###THEORETICAL QUESTIONS

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Purpose: NumPy is a fundamental library for scientific computing in Python, providing support for large, multi-dimensional arrays and matrices.

Advantages:
-->Performance: NumPy operations are implemented in C, making them faster than standard Python loops.
-->Convenience: It offers a wide range of mathematical functions and tools for array manipulation.
-->Memory Efficiency: It uses contiguous memory blocks for arrays, reducing overhead compared to Python lists.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [1]:
#np.mean(): Computes the arithmetic mean along the specified axis.
import numpy as np
arr = np.array([1, 2, 3])
print(np.mean(arr))

#np.average(): Allows weighting of elements and computes the weighted average.
weights = np.array([1, 2, 3])
print(np.average(arr, weights=weights))


#Use Case: Use np.mean() for simple averaging, and np.average() when weights are involved.


2.0
2.3333333333333335


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [2]:
#1D Array
arr1d = np.array([1, 2, 3, 4])
print(arr1d[::-1])
print("\n")

#2D Array
arr2d = np.array([[1, 2], [3, 4]])
print(arr2d[::-1])  # Reverse rows
print(arr2d[:, ::-1])  # Reverse columns

[4 3 2 1]


[[3 4]
 [1 2]]
[[2 1]
 [4 3]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.


In [3]:
#Use the .dtype attribute to determine the data type of a NumPy array.
arr = np.array([1, 2, 3], dtype=float)
print(arr.dtype)

#Importance: Data types influence memory usage and performance. For example, using float32 instead of float64 saves memory.


float64


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarray: NumPy's core data structure representing n-dimensional arrays.

Key Features:
-->Homogeneous data types.
-->Fixed size.
-->Supports vectorized operations.

Difference from Lists: Unlike Python lists, ndarrays have a fixed size and are more memory-efficient and faster for numerical operations.


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays are faster than Python lists for large-scale numerical operations due to:
-->Contiguous memory storage: Better cache performance.
-->Optimized operations: Built-in functions are implemented in C, avoiding Python overhead.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In [4]:
#np.vstack(): Stacks arrays vertically (row-wise).
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
print(np.vstack((arr1, arr2)))  # Output: [[1, 2], [3, 4], [5, 6]]

#np.hstack(): Stacks arrays horizontally (column-wise).
arr3 = np.array([[7], [8]])
print(np.hstack((arr1, arr3)))  # Output: [[1, 2, 7], [3, 4, 8]]


[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In [6]:
#np.fliplr(): Flips an array left to right.
arr = np.array([[1, 2], [3, 4]])
print(np.fliplr(arr))  # Output: [[2, 1], [4, 3]]

#np.flipud(): Flips an array up to down.
print(np.flipud(arr))  # Output: [[3, 4], [1, 2]]

[[2 1]
 [4 3]]
[[3 4]
 [1 2]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [7]:
#np.array_split() splits an array into multiple sub-arrays. It handles uneven splits by distributing leftover elements among the splits.
arr = np.array([1, 2, 3, 4, 5])
splits = np.array_split(arr, 3)
print(splits)

[array([1, 2]), array([3, 4]), array([5])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [8]:
#Vectorization: Refers to operations applied to entire arrays rather than element-wise loops, significantly speeding up computations.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Output: [5, 7, 9]

#Broadcasting: Allows NumPy to perform operations on arrays of different shapes, making it possible to work with arrays without explicit replication.
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a + b)  # Output: [[2, 3, 4], [3, 4, 5], [4, 5, 6]]

#Both concepts enhance efficiency and simplify code for array operations.

[5 7 9]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


###PRACTICAL QUESTION

1.  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [9]:
import numpy as np

arr1 = np.random.randint(1, 101, size = (3, 3))
print("Original array:")
print(arr1)
print("\n")
arr1.T
print("Transposed array:")
print(arr1)

Original array:
[[ 62  48  10]
 [ 12  58 100]
 [ 29  60  47]]


Transposed array:
[[ 62  48  10]
 [ 12  58 100]
 [ 29  60  47]]


2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [10]:
res = np.random.random_sample((10, ))
print(res)
print("\n")

res1 = res.reshape(2, 5)
print(res1)
print("\n")

res.reshape(2, 5).base
res2 = res.reshape(5, 2)
print(res2)

[0.71334776 0.24971295 0.83695511 0.69155881 0.6817436  0.67145249
 0.71042767 0.79434575 0.84245361 0.30251079]


[[0.71334776 0.24971295 0.83695511 0.69155881 0.6817436 ]
 [0.67145249 0.71042767 0.79434575 0.84245361 0.30251079]]


[[0.71334776 0.24971295]
 [0.83695511 0.69155881]
 [0.6817436  0.67145249]
 [0.71042767 0.79434575]
 [0.84245361 0.30251079]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


In [11]:
# Create a 4x4 array with random float values
original_array = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(original_array)

# Add a border of zeros around the original array
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Border of Zeros:")
print(bordered_array)

# Create a 4x4 array with random float values
original_array = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(original_array)

# Add a border of zeros around the original array
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Border of Zeros:")
print(bordered_array)


Original 4x4 Array:
[[0.49361143 0.69037487 0.64109415 0.47352434]
 [0.63181605 0.39155002 0.97756157 0.13425077]
 [0.55621779 0.21942977 0.24346275 0.0702431 ]
 [0.61924597 0.10997156 0.7775461  0.82859929]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.49361143 0.69037487 0.64109415 0.47352434 0.        ]
 [0.         0.63181605 0.39155002 0.97756157 0.13425077 0.        ]
 [0.         0.55621779 0.21942977 0.24346275 0.0702431  0.        ]
 [0.         0.61924597 0.10997156 0.7775461  0.82859929 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
Original 4x4 Array:
[[0.40372606 0.51629024 0.36123669 0.20141174]
 [0.0315667  0.74794035 0.61547296 0.71373597]
 [0.60008909 0.59203081 0.53743926 0.02305552]
 [0.80316689 0.56676436 0.60986028 0.65203402]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.40372606 0.516290

4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [12]:
arr = np.arange(10, 60, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55]


5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [13]:
# Create a NumPy array of strings
words = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(words)
lowercase = np.char.lower(words)
titlecase = np.char.title(words)
capitalize = np.char.capitalize(words)

# Display the results
print("Original Words:")
print(words)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitle Case:")
print(titlecase)

print("\nCapitalized:")
print(capitalize)

Original Words:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [14]:
# Generate a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array', 'example'])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

print("Original Words:")
print(words)
print("\nWords with Spaces Between Characters:")
print(spaced_words)

Original Words:
['hello' 'world' 'numpy' 'array' 'example']

Words with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y' 'e x a m p l e']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [15]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))
print(arr1.ndim)
print(arr2.ndim)
print("\n")

#add element/index wise
print(arr1+arr2)
print("\n")

#subtract: index wise
print(arr1 - arr2)
print("\n")

#multiplication: index wise
print(arr1 * arr2)
print("\n")

#Division: indexwise
print(arr1/arr2)

2
2


[[4 3 2]
 [3 4 4]
 [3 2 2]]


[[0 1 0]
 [1 0 0]
 [1 0 0]]


[[4 2 1]
 [2 4 4]
 [2 1 1]]


[[1. 2. 1.]
 [2. 1. 1.]
 [2. 1. 1.]]


8.  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [16]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [17]:
random_array = np.random.randint(0, 1001, size=100)
print("Random Array:")
print(random_array)

# Find all prime numbers in the array
prime_numbers = []

for num in random_array:
    if num > 1:  # Check if the number is greater than 1
        is_prime = True
        for i in range(2, int(num**0.5) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            prime_numbers.append(num)

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Array:
[253 710 300 312 941 767 319 598 560 389 948 772 116 829  60 646 537 761
 940 765 894 486 578 849 608 793  51 780 676  79 598 455 443 991 429  42
 889 225 281 858 325 304  48 175 815 746 595 618 909 859 996 145 723 165
  25  26 780 915 162  45 218  45 828 982 810 819 518 244 117 629 276 741
 262 253  25 955 714 440 259 122 378 315 860 556 820 940 563 953 922 814
 113 145 123 103 510 540 965 119 226 839]

Prime Numbers in the Array:
[941, 389, 829, 761, 79, 443, 991, 281, 859, 563, 953, 113, 103, 839]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [18]:
# Create a NumPy array representing daily temperatures for 30 days
# For example, temperatures between 0 and 100 degrees
daily_temperatures = np.random.uniform(0, 100, size=30)
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array into weeks (4 weeks of 7 days, plus 2 extra days)
# We will ignore the last 2 days for averaging purposes
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Weekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[73.67803802 57.3596509  55.48902464 78.26391545 66.51528844 36.65449463
  5.14629574 31.36220118 55.40605138 42.90111415 48.25733479 15.65642156
 24.43669816 37.76970401 35.20126867 49.4757439  44.14744993 58.15638944
 37.99922479  4.46972755 70.47208901 15.79702475 48.74989241 14.35478698
 62.28922476 67.12259443 54.86760501 84.33156586 76.4850517  43.15866922]
Weekly Averages:
[53.30095826 36.54136075 42.84598476 49.6446706 ]
